### ISSUE TITLE
docs-implement-swagger-open-api

### ISSUE THREAD

**Issue by colinwilliams91** [hotfix-studios/scrum-poker#31]
### <h2>Describe the Problem</h2>

Front End and Back End teams are siloed and have HTTP requests going back and forth over dynamic and evolving routes.

Manually documenting this is difficult.

### <h2>Describe the Proposed Solution</h2>

Implementing 
- [swagger](https://swagger.io/)
  - 78k downloads/week npm
  - `npm i swagger-ui`
  - repository - [swagger-ui](https://github.com/swagger-api/swagger-ui)

OR 

- [redoc](https://redocly.com/redoc/)
  - 311k downloads/week npm
  - `npm i redoc`
  - supports JSON & C#
  - [npm + readme](https://www.npmjs.com/package/redoc)

more redoc [docs](https://redocly.com/docs/redoc/)
and redoc [configuration reference](https://redocly.com/docs/redoc/config/)

#### Redoc

![Image](https://github.com/hotfix-studios/scrum-poker/assets/92059005/80d1b6eb-8ab6-4007-8006-7a614773a6e6)

#### Swagger

![Image](https://github.com/hotfix-studios/scrum-poker/assets/92059005/400c1f5d-b9b7-4811-a652-03744e12aa16)

**Comment by colinwilliams91** [comment]
Here's a sample `redocly.yaml` configuration file, showing a few common settings and tweaking some of the visual theme settings:
```yaml
theme:
  openapi:
    disableSearch: true
    expandResponses: 200,202
    jsonSampleExpandLevel: 1

    theme:
      sidebar:
        backgroundColor: '#eae0cc'
        textColor: '#3d005b'
      colors:
        primary:
          main: '#660099'
      typography:
        fontSize: 14pt
        headings:
          fontWeight: bold
```
